name: Github API
on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # リポジトリの中身を読むために必要
      pull-requests: write  # PRへのコメントを書き込むために必要
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${{ GITHUB_HEAD_REF }}"" --body "Hello, ${GITHUB_ACTOR}!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
