name: Override Environment Variables
on: push
env:
  EXAMPLE: Definedby workflow level
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "EXAMPLE=${EXAMPLE}"
      - env:
          EXAMPLE: Defined by job level
        run: echo "EXAMPLE=${EXAMPLE}"
