name: Sequential jobs
on: push
jobs: 
  first:  # 依存jobがないので最初に実行される
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "This is the first job"
  second:
    runs-on: ubuntu-latest
    needs: first  # first jobが完了した後に実行される
    steps:
      - run: sleep 10 && echo "This is the second job"
  third:
    runs-on: ubuntu-latest
    needs: second  # second jobが完了した後に実行される
    steps:
      - run: sleep 10 && echo "This is the third job"
