name: Static Analysis
on:
  pull_request:
    paths: ['.github/workflows/*.yml', .github/workflows/*.yaml]
defaults:
  run:
    shell: bash  # デフォルトのシェルを bash に設定しておく
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # 古いジョブをキャンセルする
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # タイムアウト時間を3分に設定
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
